### Enter进入编辑模式，Esc退出编辑模式
    a 插入cell above      b 插入cell blow
    m 转成MarkDown格式    r 转成Raw NBconvert格式
    dd 删除一行
    j上移   k下移
    Shift+Enter 执行，并移到下一行
    Ctrl+Enter  执行，留在当前行
    Tab可以提示
    o 将结果收起

In [1]:
import numpy as np

### 数组与标量运算 每个元素分别于标量进行运算

In [2]:
arr1= np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [3]:
arr1+2

array([[ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12]])

In [4]:
arr1*3

array([[ 3,  6,  9, 12, 15],
       [18, 21, 24, 27, 30]])

In [5]:
arr1**2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]])

In [6]:
1/arr1

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [7]:
from __future__ import division

In [8]:
1/arr1

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ,  0.2       ],
       [ 0.16666667,  0.14285714,  0.125     ,  0.11111111,  0.1       ]])

### 大小相等数组之间运算  数组对应元素之间进行运算 

In [9]:
arr1=np.array([3,4,5,6])

In [10]:
arr2=np.array([7,8,9,0])

In [11]:
arr1+arr2

array([10, 12, 14,  6])

In [12]:
arr1-arr2

array([-4, -4, -4,  6])

In [13]:
arr1*arr2

array([21, 32, 45,  0])

In [14]:
arr2/arr1

array([ 2.33333333,  2.        ,  1.8       ,  0.        ])

### 矩阵积 dot 
    两个二维矩阵，满足第一个矩阵的列数与第二个矩阵的行数相同，可以进行矩阵乘法
    第一个矩阵的行和第二个矩阵的列元素对应积之和

In [15]:
arr3=np.random.random((4,1))

In [16]:
arr3

array([[ 0.16435611],
       [ 0.70601388],
       [ 0.65169511],
       [ 0.29497968]])

In [17]:
arr1.dot(arr3)

array([ 8.34547749])

### 多维数组的索引   从0开始

In [18]:
arr=np.random.random((2,3,4))

In [19]:
arr

array([[[ 0.51584225,  0.51215201,  0.50203365,  0.73589224],
        [ 0.3639266 ,  0.711008  ,  0.6348151 ,  0.5675865 ],
        [ 0.75373814,  0.53705895,  0.87682732,  0.21791088]],

       [[ 0.43907679,  0.75591269,  0.87815739,  0.23430679],
        [ 0.07226454,  0.99449955,  0.76128755,  0.22292403],
        [ 0.392307  ,  0.90244115,  0.62707448,  0.17788047]]])

In [20]:
arr[1][0][2]

0.87815739355740574

In [21]:
arr[1,0,2]

0.87815739355740574

### NumPy数组中的切片  1:3 范围包头不包尾

In [22]:
arr[0,:,1:3]

array([[ 0.51215201,  0.50203365],
       [ 0.711008  ,  0.6348151 ],
       [ 0.53705895,  0.87682732]])

In [23]:
arr[0,1:2,1:3]

array([[ 0.711008 ,  0.6348151]])

In [24]:
arr[0,1:3,1:3]

array([[ 0.711008  ,  0.6348151 ],
       [ 0.53705895,  0.87682732]])

### 布尔型索引

In [25]:
arr<0.5

array([[[False, False, False, False],
        [ True, False, False, False],
        [False, False, False,  True]],

       [[ True, False, False,  True],
        [ True, False, False,  True],
        [ True, False, False,  True]]], dtype=bool)

In [26]:
arr[arr<0.5]

array([ 0.3639266 ,  0.21791088,  0.43907679,  0.23430679,  0.07226454,
        0.22292403,  0.392307  ,  0.17788047])

In [27]:
names=np.array(["Merry","Jully","Frank"])

In [28]:
names=="Frank"

array([False, False,  True], dtype=bool)

In [29]:
scores=np.array([[99,100,89,72],[88,98,93,89]])

In [30]:
names=names[1:3]

In [31]:
names

array(['Jully', 'Frank'], 
      dtype='|S5')

In [32]:
scores[names=="Frank"]

array([[88, 98, 93, 89]])

### 花式索引    利用整数数组进行做引

In [33]:
arr=np.arange(32).reshape(8,4)

In [34]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [35]:
arr[[0,3,5]]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [37]:
arr[0,3]

3

In [38]:
arr[[0,3,5],[0,3,2]]

array([ 0, 15, 22])

### ix_函数产生一个索引器

In [41]:
arr[np.ix_([0,3,5],[0,3,2])]

array([[ 0,  3,  2],
       [12, 15, 14],
       [20, 23, 22]])

### transpose()    转置

In [42]:
arr.transpose()

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [43]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

### 数组的T属性 也是转置

In [44]:
arr.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [3]:
help(np.ix_)

Help on function ix_ in module numpy.lib.index_tricks:

ix_(*args)
    Construct an open mesh from multiple sequences.
    
    This function takes N 1-D sequences and returns N outputs with N
    dimensions each, such that the shape is 1 in all but one dimension
    and the dimension with the non-unit shape value cycles through all
    N dimensions.
    
    Using `ix_` one can quickly construct index arrays that will index
    the cross product. ``a[np.ix_([1,3],[2,5])]`` returns the array
    ``[[a[1,2] a[1,5]], [a[3,2] a[3,5]]]``.
    
    Parameters
    ----------
    args : 1-D sequences
    
    Returns
    -------
    out : tuple of ndarrays
        N arrays with N dimensions each, with N the number of input
        sequences. Together these arrays form an open mesh.
    
    See Also
    --------
    ogrid, mgrid, meshgrid
    
    Examples
    --------
    >>> a = np.arange(10).reshape(2, 5)
    >>> a
    array([[0, 1, 2, 3, 4],
           [5, 6, 7, 8, 9]])
    >>> ixgrid = n