# NumPy

#### Numberical Python,数值Python包，是Python进行科学计算的基础包
    NumPy系统是Python的一种开源数值计算扩展，提供了许多高级的数值编程工具，如：矩阵数据类型，矢量处理，精密的运算库。转为进行严格的数字处理而产生
    Anaconda版Python已经预装好了NumPy模块

## 依照标准约定，导入numpy方式

In [2]:
import numpy as np

### ndarray N维数组

In [47]:
a0=np.array([(0,1,2,3,4),(1,2,3,4,5),(6,7,8,9,0)])

In [48]:
a0

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

#### ndarray标准形式 np.array([……])
    外层必须是(),内层用[]括起来，内层可以用[]也可以用()
    内层每增加一层，则维度增加一维

In [27]:
a0=np.array((0,1,2,3,4),[5,6,7,8,9])

TypeError: data type not understood

In [34]:
a0=np.array[[(0,1,2,3,4),[5,6,7,8,9]]]

TypeError: 'builtin_function_or_method' object has no attribute '__getitem__'

### 维度
    按层数算

In [17]:
a0.ndim

2

In [3]:
a0=np.array((0,1,2,3,4))

In [38]:
a0.ndim

1

In [39]:
a0=np.array([(0,1,2,3,4),(1,2,3,4,5),(6,7,8,9,0),(1,2,3,4,5)])

In [40]:
a0.ndim

2

重复的圆括号没有意义，但是重复的方括号代表增加一维

In [29]:
a0=np.array(((0,1,2,3)))

In [30]:
a0.ndim

1

In [17]:
a0.shape

(4L,)

In [24]:
a1=np.array([[1,2,3,4]])

In [31]:
a1.ndim

2

In [32]:
a1.shape

(1L, 4L)

In [26]:
a2=np.array([(0,1,2,3)])

In [27]:
a2.ndim

2

In [21]:
a=np.zeros((1,4))

In [22]:
a

array([[ 0.,  0.,  0.,  0.]])

In [23]:
a.ndim

2

In [33]:
a3=np.zeros((1,1,1,1))

In [34]:
a3

array([[[[ 0.]]]])

In [36]:
a4=np.array([((1,2))])

In [37]:
a4.ndim

2

### 形状
    对应每一维的元素个数

In [52]:
a0.shape

(4L,)

### 数据类型

In [9]:
a0.dtype

dtype('int32')

### 元素总个数

In [10]:
a0.size

15

In [12]:
a=np.array([
 [
     [3.4,5,6,8],
     [3,2.4,5,7]
 ],
 [
     [2.3,4,5,6],
     [0.9,5,6,1]
 ],
 [
     [9,6.7,3,2],
     [1,3,4,5]
 ]   
])

### a 3维 (3,2,4)

In [13]:
a

array([[[ 3.4,  5. ,  6. ,  8. ],
        [ 3. ,  2.4,  5. ,  7. ]],

       [[ 2.3,  4. ,  5. ,  6. ],
        [ 0.9,  5. ,  6. ,  1. ]],

       [[ 9. ,  6.7,  3. ,  2. ],
        [ 1. ,  3. ,  4. ,  5. ]]])

In [14]:
a.ndim

3

In [15]:
a.shape

(3L, 2L, 4L)

In [15]:
a.size

24

In [16]:
a.dtype

dtype('float64')

### a1 3维 (2,4,4)

In [17]:
a1=np.array([
    [
        [1,2,3,4],
        [3,4,5,6],
        [4,5,6,7],
        [9,4,5,6]
    ],
    [
        [9,8,4,5],
        [4,6,7,9],
        [9,5,3,1],
        [7,5,6,1]
    ]
],dtype=float)

In [18]:
a1

array([[[ 1.,  2.,  3.,  4.],
        [ 3.,  4.,  5.,  6.],
        [ 4.,  5.,  6.,  7.],
        [ 9.,  4.,  5.,  6.]],

       [[ 9.,  8.,  4.,  5.],
        [ 4.,  6.,  7.,  9.],
        [ 9.,  5.,  3.,  1.],
        [ 7.,  5.,  6.,  1.]]])

In [19]:
a1.ndim

3

In [20]:
a1.shape

(2L, 4L, 4L)

In [21]:
a1.ndim

3

In [28]:
a1.dtype

dtype('float64')

### a2 3维 (4,2,4)

In [23]:
a2=np.array([
 [
     [3.4,5,6,8],
     [3,2.4,5,7]
 ],
 [
     [2.3,4,5,6],
     [0.9,5,6,1]
 ],
 [
     [9,6.7,3,2],
     [1,3,4,5]
 ],
 [
     [9,6.7,3,2],
     [1,3,4,5]
 ]
])

In [24]:
a2.ndim

3

In [25]:
a2.shape

(4L, 2L, 4L)

In [26]:
a2.size

32

In [27]:
a2.dtype

dtype('float64')

### ()也可以

In [29]:
b=np.array((
    (
        (1,2,3,4),
        (4,5,6,7),
        (9,3,4,5)
    ),
    (
        (0,2,3,4),
        (1,4,7,8),
        (4,5,3,2)
    )
))

In [30]:
b.ndim

3

In [31]:
b.shape

(2L, 3L, 4L)

In [32]:
b.dtype

dtype('int32')

In [33]:
b.size

24

### zeros
    np.zeros(……)
    除非是1维，否则内层也要有括号包裹,()/[]都可以，外层都是()

In [11]:
a=np.zeros(4)

In [12]:
a.ndim

1

In [13]:
a

array([ 0.,  0.,  0.,  0.])

In [53]:
np.zeros(3,4)

TypeError: data type not understood

In [59]:
np.zeros([3,4])

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [36]:
np.zeros((3,2,4))

array([[[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])

### ones

In [40]:
np.ones((2,3,2))

array([[[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]]])

In [41]:
Out[40].dtype

dtype('float64')

### empty

In [42]:
np.empty((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

### arange() 包头不包尾

In [22]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [29]:
np.arange(3,10,2)

array([3, 5, 7, 9])

In [30]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### linspace

In [39]:
np.linspace(0,19,3)

array([  0. ,   9.5,  19. ])

### help 查看函数用法

In [32]:
help(np.arange)

Help on built-in function arange in module numpy.core.multiarray:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range <http://docs.python.org/lib/built-in-funcs.html>`_ function,
    but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use ``linspace`` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and

### logspace() 10的幂，分段,等比数列

In [33]:
np.logspace(0,2,5)

array([   1.        ,    3.16227766,   10.        ,   31.6227766 ,  100.        ])

In [62]:
help(np.logspace)

Help on function logspace in module numpy.core.function_base:

logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
    Return numbers spaced evenly on a log scale.
    
    In linear space, the sequence starts at ``base ** start``
    (`base` to the power of `start`) and ends with ``base ** stop``
    (see `endpoint` below).
    
    Parameters
    ----------
    start : float
        ``base ** start`` is the starting value of the sequence.
    stop : float
        ``base ** stop`` is the final value of the sequence, unless `endpoint`
        is False.  In that case, ``num + 1`` values are spaced over the
        interval in log-space, of which all but the last (a sequence of
        length ``num``) are returned.
    num : integer, optional
        Number of samples to generate.  Default is 50.
    endpoint : boolean, optional
        If true, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
    base : float, optional
        The base o

### random 

In [51]:
np.random.random((3,1,3))

array([[[ 0.6561433 ,  0.12548632,  0.71300668]],

       [[ 0.83988424,  0.30209873,  0.9510697 ]],

       [[ 0.96608753,  0.33805635,  0.15364467]]])

In [53]:
np.random.random((3,2,3))

array([[[ 0.11200969,  0.52379667,  0.45603186],
        [ 0.10015779,  0.63488035,  0.97378089]],

       [[ 0.52322351,  0.99019093,  0.67112404],
        [ 0.30227185,  0.72630772,  0.71315591]],

       [[ 0.7021641 ,  0.92267659,  0.66043373],
        [ 0.13189928,  0.15647933,  0.03042841]]])

In [59]:
aa=np.array([[1,2,3,4],[2,2,2,2]])

In [60]:
aa.ndim

2

### dtype 查看数据类型

In [61]:
aa.dtype

dtype('int32')

### astype 类型转换

In [64]:
bb=aa.astype(float)

In [63]:
aa.dtype

dtype('int32')

In [65]:
bb.dtype

dtype('float64')

In [67]:
bb.astype(int).dtype

dtype('int32')

### 数据类型

In [68]:
d= np.array(["Python","Scala"])

In [69]:
d.dtype

dtype('S6')

In [70]:
d

array(['Python', 'Scala'], 
      dtype='|S6')

### reshape() 自身形状不变，产生新的ndarray；  shape 改变自身形状
    指定某个轴元素为-1时，将自动计算此轴的长度

In [40]:
a=np.random.random((2,4))

In [41]:
a

array([[ 0.02073476,  0.95113463,  0.40126481,  0.53449068],
       [ 0.73899854,  0.67199949,  0.77539334,  0.79715743]])

In [42]:
a.shape= 4,-1

In [43]:
a

array([[ 0.02073476,  0.95113463],
       [ 0.40126481,  0.53449068],
       [ 0.73899854,  0.67199949],
       [ 0.77539334,  0.79715743]])

In [77]:
a.reshape(2,2,2)

array([[[ 0.11424942,  0.80471035],
        [ 0.42388582,  0.29694287]],

       [[ 0.38508648,  0.84034799],
        [ 0.7897197 ,  0.52415223]]])

In [78]:
a

array([[ 0.11424942,  0.80471035],
       [ 0.42388582,  0.29694287],
       [ 0.38508648,  0.84034799],
       [ 0.7897197 ,  0.52415223]])