### ufunc 函数，数组存储到磁盘及从磁盘中读取

In [1]:
import numpy as np

### ufunc 对ndarray中的数据执行元素级运算的函数
    简单函数的矢量化包装器

In [4]:
arr=np.arange(32).reshape(4,8)

In [5]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [6]:
np.sqrt(arr)

array([[ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
         2.23606798,  2.44948974,  2.64575131],
       [ 2.82842712,  3.        ,  3.16227766,  3.31662479,  3.46410162,
         3.60555128,  3.74165739,  3.87298335],
       [ 4.        ,  4.12310563,  4.24264069,  4.35889894,  4.47213595,
         4.58257569,  4.69041576,  4.79583152],
       [ 4.89897949,  5.        ,  5.09901951,  5.19615242,  5.29150262,
         5.38516481,  5.47722558,  5.56776436]])

In [7]:
help(np.exp)

Help on ufunc object:

exp = class ufunc(__builtin__.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use np.info().  For
 |  example, np.info(np.sin).  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the "ufuncs.rst"
 |  file in the NumPy reference guide.
 |  
 |  Unary ufuncs:
 |  =============
 |  
 |  op(X, out=None)
 |  Apply op to X elementwise
 |  
 |  Parameters
 |  ----------
 |  X : array_like
 |      Input array.
 |  out : array_like
 |      An array to store the output. Must be the same shape as `X`.
 |  
 |  Returns
 |  -------
 |  r : array_like
 |      `r` will have the same shape as `X`; if out is provided, `r`
 |      will be equal to out.
 |  
 |  Binary ufuncs:
 |  ==============
 |  
 |  op(X, Y,

In [8]:
np.info(np.exp)

exp(x[, out])

Calculate the exponential of all elements in the input array.

Parameters
----------
x : array_like
    Input values.

Returns
-------
out : ndarray
    Output array, element-wise exponential of `x`.

See Also
--------
expm1 : Calculate ``exp(x) - 1`` for all elements in the array.
exp2  : Calculate ``2**x`` for all elements in the array.

Notes
-----
The irrational number ``e`` is also known as Euler's number.  It is
approximately 2.718281, and is the base of the natural logarithm,
``ln`` (this means that, if :math:`x = \ln y = \log_e y`,
then :math:`e^x = y`. For real input, ``exp(x)`` is always positive.

For complex arguments, ``x = a + ib``, we can write
:math:`e^x = e^a e^{ib}`.  The first term, :math:`e^a`, is already
known (it is the real argument, described above).  The second term,
:math:`e^{ib}`, is :math:`\cos b + i \sin b`, a function with
magnitude 1 and a periodic phase.

References
----------
.. [1] Wikipedia, "Exponential function",
       http://en.wiki

In [9]:
np.exp(arr)

array([[  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
          2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
          4.03428793e+02,   1.09663316e+03],
       [  2.98095799e+03,   8.10308393e+03,   2.20264658e+04,
          5.98741417e+04,   1.62754791e+05,   4.42413392e+05,
          1.20260428e+06,   3.26901737e+06],
       [  8.88611052e+06,   2.41549528e+07,   6.56599691e+07,
          1.78482301e+08,   4.85165195e+08,   1.31881573e+09,
          3.58491285e+09,   9.74480345e+09],
       [  2.64891221e+10,   7.20048993e+10,   1.95729609e+11,
          5.32048241e+11,   1.44625706e+12,   3.93133430e+12,
          1.06864746e+13,   2.90488497e+13]])

In [10]:
arr=np.arange(8).reshape(2,-1)

In [11]:
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [12]:
arr.mean()

3.5

### axis=0 对同一列的元素聚合
### axis=1 对同一行的元素聚合

In [13]:
arr.mean(axis=0)

array([ 2.,  3.,  4.,  5.])

In [14]:
arr.mean(axis=1)

array([ 1.5,  5.5])

In [15]:
arr.sum

<function sum>

In [16]:
arr.sum()

28

In [17]:
arr.sum(axis=0)

array([ 4,  6,  8, 10])

In [18]:
arr.sum(axis=1)

array([ 6, 22])

In [21]:
arr=np.arange(24).reshape(3,4,2)

In [22]:
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [23]:
arr.sum(axis=0)

array([[24, 27],
       [30, 33],
       [36, 39],
       [42, 45]])

In [24]:
arr.sum(axis=1)

array([[12, 16],
       [44, 48],
       [76, 80]])

### np.where()
    三元表达式 x if condition else y 的矢量化版本

In [25]:
condition=np.array([1,0,1,1,0])

In [26]:
condition>0

array([ True, False,  True,  True, False], dtype=bool)

In [27]:
condition=condition>0

In [28]:
condition

array([ True, False,  True,  True, False], dtype=bool)

In [31]:
xarr=np.arange(1.1,1.6,0.1)

In [32]:
xarr

array([ 1.1,  1.2,  1.3,  1.4,  1.5])

In [33]:
yarr=np.arange(2.1,2.6,0.1)

In [34]:
yarr

array([ 2.1,  2.2,  2.3,  2.4,  2.5])

In [35]:
result=[(x if c else y) for  x,y,c in zip(xarr,yarr,condition)]

In [36]:
result

[1.1000000000000001,
 2.2000000000000002,
 1.3000000000000003,
 1.4000000000000004,
 2.5000000000000004]

In [37]:
result = np.where(condition,xarr,yarr)

In [38]:
result

array([ 1.1,  2.2,  1.3,  1.4,  2.5])

In [39]:
arr=np.array([[1,2,np.NaN,4],[3,4,5,np.NaN]])

In [40]:
arr

array([[  1.,   2.,  nan,   4.],
       [  3.,   4.,   5.,  nan]])

In [42]:
np.isnan(arr)

array([[False, False,  True, False],
       [False, False, False,  True]], dtype=bool)

In [46]:
arr=np.where(np.isnan(arr),0,arr)

In [47]:
arr

array([[ 1.,  2.,  0.,  4.],
       [ 3.,  4.,  5.,  0.]])

### np.unique()  求数组中不重复的元素

In [53]:
productTypes=np.array(['图书','数码','小吃','美食','数码','男装'])

In [54]:
productTypes

array(['\xe5\x9b\xbe\xe4\xb9\xa6', '\xe6\x95\xb0\xe7\xa0\x81',
       '\xe5\xb0\x8f\xe5\x90\x83', '\xe7\xbe\x8e\xe9\xa3\x9f',
       '\xe6\x95\xb0\xe7\xa0\x81', '\xe7\x94\xb7\xe8\xa3\x85'], 
      dtype='|S6')

In [55]:
np.unique(productTypes)

array(['\xe5\x9b\xbe\xe4\xb9\xa6', '\xe5\xb0\x8f\xe5\x90\x83',
       '\xe6\x95\xb0\xe7\xa0\x81', '\xe7\x94\xb7\xe8\xa3\x85',
       '\xe7\xbe\x8e\xe9\xa3\x9f'], 
      dtype='|S6')

In [56]:
for pt in np.unique(productTypes):
    print pt

图书
小吃
数码
男装
美食


### 数组数据读写 
    将数组以二进制格式存取
    存取文本文件

#### 二进制存储   .npy格式

In [57]:
data= np.arange(16).reshape(4,-1)

In [58]:
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [59]:
np.save('mydata',data)

In [65]:
data.shape=8,-1

In [66]:
data

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [67]:
np.load('mydata.npy')

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [68]:
data

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

### 为何存储的是int32格式，读取时变为<f8格式？

#### 文本格式存储  

In [69]:
np.savetxt('data.csv',data,delimiter=',')

In [70]:
np.loadtxt('data.csv',delimiter=',')

array([[  0.,   1.],
       [  2.,   3.],
       [  4.,   5.],
       [  6.,   7.],
       [  8.,   9.],
       [ 10.,  11.],
       [ 12.,  13.],
       [ 14.,  15.]])

In [71]:
np.genfromtxt('data.csv',delimiter=',')

array([[  0.,   1.],
       [  2.,   3.],
       [  4.,   5.],
       [  6.,   7.],
       [  8.,   9.],
       [ 10.,  11.],
       [ 12.,  13.],
       [ 14.,  15.]])

In [74]:
gdps=np.genfromtxt('data.csv',delimiter=',',names=True)

In [75]:
gdps

array([(2.0, 3.0), (4.0, 5.0), (6.0, 7.0), (8.0, 9.0), (10.0, 11.0),
       (12.0, 13.0), (14.0, 15.0)], 
      dtype=[('0000000000000000000e00', '<f8'), ('1000000000000000000e00', '<f8')])

In [79]:
gdps['0']

ValueError: no field of name 0

In [80]:
data.dtype

dtype('int32')

In [81]:
gdps.dtype

dtype([('0000000000000000000e00', '<f8'), ('1000000000000000000e00', '<f8')])

In [82]:
gdps=np.genfromtxt('mydata.csv',delimiter=',',names=True)

In [83]:
gdps

array([(2.0, 4.0, 8.0, 7.0), (3.0, 4.0, 2.0, 5.0), (8.0, 3.0, 4.0, 9.0)], 
      dtype=[('2007', '<f8'), ('2008', '<f8'), ('2009', '<f8'), ('2010', '<f8')])

In [84]:
gdps['2007']

array([ 2.,  3.,  8.])

In [85]:
gdps[0]

(2.0, 4.0, 8.0, 7.0)