# NumPy

#### Numberical Python,数值Python包，是Python进行科学计算的基础包
    NumPy系统是Python的一种开源数值计算扩展，提供了许多高级的数值编程工具，如：矩阵数据类型，矢量处理，精密的运算库。转为进行严格的数字处理而产生
    Anaconda版Python已经预装好了NumPy模块

## 依照标准约定，导入numpy方式

In [1]:
import numpy as np

### ndarray N维数组

In [2]:
a0=np.array([(0,1,2,3,4),(1,2,3,4,5),(6,7,8,9,0)])

In [3]:
a0

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

#### ndarray标准形式 np.array([……])
    外层必须是(),内层用[]括起来，内层可以用[]也可以用()
    内层每增加一层，则维度增加一维

In [12]:
a0=np.array([(0,1,2,3,4),[5,6,7,8,9]])

In [13]:
a0=np.array[[(0,1,2,3,4),[5,6,7,8,9]]]

TypeError: 'builtin_function_or_method' object has no attribute '__getitem__'

### 维度
    按层数算

In [14]:
a0.ndim

2

In [15]:
a0=np.array((0,1,2,3,4))

In [16]:
a0.ndim

1

In [17]:
a0=np.array([(0,1,2,3,4),(1,2,3,4,5),(6,7,8,9,0),(1,2,3,4,5)])

In [18]:
a0.ndim

2

重复的圆括号没有意义，但是重复的方括号代表增加一维

In [19]:
a0=np.array(((0,1,2,3)))

In [20]:
a0.ndim

1

In [21]:
a0.shape

(4L,)

In [22]:
a0=np.array([(1,2)])

In [23]:
a0.ndim

2

In [24]:
a1=np.array([[1,2,3,4]])

In [25]:
a1.ndim

2

In [26]:
a1.shape

(1L, 4L)

In [27]:
a2=np.array([(0,1,2,3)])

In [28]:
a2.ndim

2

In [29]:
a=np.zeros((1,4))

In [30]:
a

array([[ 0.,  0.,  0.,  0.]])

In [31]:
a.ndim

2

In [32]:
a=np.zeros(4)

In [33]:
a

array([ 0.,  0.,  0.,  0.])

In [34]:
a.ndim

1

In [35]:
a3=np.zeros((1,1,1,1))

In [36]:
a3

array([[[[ 0.]]]])

In [37]:
a4=np.array([([1,2])])

In [38]:
a4.ndim

2

### 形状
    对应每一维的元素个数

In [39]:
a0.shape

(1L, 2L)

### 数据类型

In [40]:
a0.dtype

dtype('int32')

### 元素总个数

In [41]:
a0.size

2

In [42]:
a=np.array([
 [
     [3.4,5,6,8],
     [3,2.4,5,7]
 ],
 [
     [2.3,4,5,6],
     [0.9,5,6,1]
 ],
 [
     [9,6.7,3,2],
     [1,3,4,5]
 ]   
])

### a 3维 (3,2,4)

In [43]:
a

array([[[ 3.4,  5. ,  6. ,  8. ],
        [ 3. ,  2.4,  5. ,  7. ]],

       [[ 2.3,  4. ,  5. ,  6. ],
        [ 0.9,  5. ,  6. ,  1. ]],

       [[ 9. ,  6.7,  3. ,  2. ],
        [ 1. ,  3. ,  4. ,  5. ]]])

In [44]:
a.ndim

3

In [45]:
a.shape

(3L, 2L, 4L)

In [46]:
a.size

24

In [47]:
a.dtype

dtype('float64')

### a1 3维 (2,4,4)

In [48]:
a1=np.array([
    [
        [1,2,3,4],
        [3,4,5,6],
        [4,5,6,7],
        [9,4,5,6]
    ],
    [
        [9,8,4,5],
        [4,6,7,9],
        [9,5,3,1],
        [7,5,6,1]
    ]
],dtype=float)

In [49]:
a1

array([[[ 1.,  2.,  3.,  4.],
        [ 3.,  4.,  5.,  6.],
        [ 4.,  5.,  6.,  7.],
        [ 9.,  4.,  5.,  6.]],

       [[ 9.,  8.,  4.,  5.],
        [ 4.,  6.,  7.,  9.],
        [ 9.,  5.,  3.,  1.],
        [ 7.,  5.,  6.,  1.]]])

In [50]:
a1.ndim

3

In [51]:
a1.shape

(2L, 4L, 4L)

In [52]:
a1.ndim

3

In [53]:
a1.dtype

dtype('float64')

### a2 3维 (4,2,4)

In [54]:
a2=np.array([
 [
     [3.4,5,6,8],
     [3,2.4,5,7]
 ],
 [
     [2.3,4,5,6],
     [0.9,5,6,1]
 ],
 [
     [9,6.7,3,2],
     [1,3,4,5]
 ],
 [
     [9,6.7,3,2],
     [1,3,4,5]
 ]
])

In [55]:
a2.ndim

3

In [56]:
a2.shape

(4L, 2L, 4L)

In [57]:
a2.size

32

In [58]:
a2.dtype

dtype('float64')

### ()也可以

In [59]:
b=np.array((
    (
        (1,2,3,4),
        (4,5,6,7),
        (9,3,4,5)
    ),
    (
        (0,2,3,4),
        (1,4,7,8),
        (4,5,3,2)
    )
))

In [60]:
b.ndim

3

In [61]:
b.shape

(2L, 3L, 4L)

In [62]:
b.dtype

dtype('int32')

In [63]:
b.size

24

### zeros
    np.zeros(……)
    除非是1维，否则内层也要有括号包裹,()/[]都可以，外层都是()

In [64]:
a=np.zeros(4)

In [65]:
a.ndim

1

In [66]:
a

array([ 0.,  0.,  0.,  0.])

In [67]:
np.zeros(3,4)

TypeError: data type not understood

In [68]:
np.zeros([3,4])

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [69]:
np.zeros((3,2,4))

array([[[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])

### ones

In [70]:
np.ones((2,3,2))

array([[[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]]])

In [72]:
np.ones((2,3,2)).dtype

dtype('float64')

### empty

In [73]:
np.empty((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

### arange() 包头不包尾

In [74]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [75]:
np.arange(3,10,2)

array([3, 5, 7, 9])

In [76]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### linspace

In [77]:
np.linspace(0,19,3)

array([  0. ,   9.5,  19. ])

### help 查看函数用法

In [78]:
help(np.arange)

Help on built-in function arange in module numpy.core.multiarray:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range <http://docs.python.org/lib/built-in-funcs.html>`_ function,
    but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use ``linspace`` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and

### logspace() 10的幂，分段,等比数列

In [79]:
np.logspace(0,2,5)

array([   1.        ,    3.16227766,   10.        ,   31.6227766 ,  100.        ])

In [80]:
help(np.logspace)

Help on function logspace in module numpy.core.function_base:

logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
    Return numbers spaced evenly on a log scale.
    
    In linear space, the sequence starts at ``base ** start``
    (`base` to the power of `start`) and ends with ``base ** stop``
    (see `endpoint` below).
    
    Parameters
    ----------
    start : float
        ``base ** start`` is the starting value of the sequence.
    stop : float
        ``base ** stop`` is the final value of the sequence, unless `endpoint`
        is False.  In that case, ``num + 1`` values are spaced over the
        interval in log-space, of which all but the last (a sequence of
        length ``num``) are returned.
    num : integer, optional
        Number of samples to generate.  Default is 50.
    endpoint : boolean, optional
        If true, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
    base : float, optional
        The base o

### random 

In [81]:
np.random.random((3,1,3))

array([[[ 0.24465121,  0.94399972,  0.12036437]],

       [[ 0.01502167,  0.66788031,  0.78751105]],

       [[ 0.6202037 ,  0.32140968,  0.46371934]]])

In [82]:
np.random.random((3,2,3))

array([[[ 0.56333066,  0.18157353,  0.30910992],
        [ 0.26071912,  0.05067293,  0.41565667]],

       [[ 0.22840932,  0.27649939,  0.66959819],
        [ 0.25485581,  0.51201737,  0.10168248]],

       [[ 0.72083695,  0.41781322,  0.01528429],
        [ 0.25075479,  0.61049769,  0.45738715]]])

In [83]:
aa=np.array([[1,2,3,4],[2,2,2,2]])

In [84]:
aa.ndim

2

### dtype 查看数据类型

In [85]:
aa.dtype

dtype('int32')

### astype 类型转换

In [86]:
bb=aa.astype(float)

In [87]:
aa.dtype

dtype('int32')

In [88]:
bb.dtype

dtype('float64')

In [89]:
bb.astype(int).dtype

dtype('int32')

### 数据类型

In [90]:
d= np.array(["Python","Scala"])

In [91]:
d.dtype

dtype('S6')

In [92]:
d

array(['Python', 'Scala'], 
      dtype='|S6')

### reshape() 自身形状不变，产生新的ndarray；  shape 改变自身形状
    指定某个轴元素为-1时，将自动计算此轴的长度

In [93]:
a=np.random.random((2,4))

In [94]:
a

array([[ 0.6414186 ,  0.9818397 ,  0.06404818,  0.61822079],
       [ 0.62544533,  0.4427162 ,  0.61991218,  0.41221091]])

In [95]:
a.shape= 4,-1

In [96]:
a

array([[ 0.6414186 ,  0.9818397 ],
       [ 0.06404818,  0.61822079],
       [ 0.62544533,  0.4427162 ],
       [ 0.61991218,  0.41221091]])

In [97]:
a.reshape(2,2,2)

array([[[ 0.6414186 ,  0.9818397 ],
        [ 0.06404818,  0.61822079]],

       [[ 0.62544533,  0.4427162 ],
        [ 0.61991218,  0.41221091]]])

In [98]:
a

array([[ 0.6414186 ,  0.9818397 ],
       [ 0.06404818,  0.61822079],
       [ 0.62544533,  0.4427162 ],
       [ 0.61991218,  0.41221091]])