In [1]:
import torch

In [2]:
from __future__ import print_function

In [3]:
x=torch.empty(5,3)

In [4]:
x

tensor(1.00000e-21 *
       [[ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 2.9168,  0.0000,  2.9168],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]])

In [5]:
x=torch.rand(5,3)

In [6]:
x

tensor([[ 0.4008,  0.5338,  0.8660],
        [ 0.7282,  0.3009,  0.1209],
        [ 0.8508,  0.4516,  0.8916],
        [ 0.7685,  0.4745,  0.9895],
        [ 0.3993,  0.2958,  0.7560]])

In [7]:
torch.zeros(5,3,dtype=torch.long)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])

In [8]:
torch.tensor([5.5,3])

tensor([ 5.5000,  3.0000])